blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
    path("blogs/", views.BlogListView.as_view(), name="blogs"),
    path("<int:pk>", views.BlogDetailView.as_view(), name="blog-detail"),
    path("create", views.create_blog_view, name="add-blog"),
    path("<int:pk>/edit", views.EditBlogView.as_view(), name="edit-blog"),
    path("<int:pk>/delete", views.DeleteBlogView.as_view(), name="delete-blog"),
    path("<int:blog_id>/delete/<int:pk>/edit", views.EditContentView.as_view(), name="edit-content"),
    path("<int:blog_id>/delete/<int:pk>/delete", views.DeleteContentView.as_view(), name="delete-content"),
    path(
        "<int:blog_id>/comment/create",
        views.AddCommentView.as_view(),
        name="add-comment",
    ),
    path(
        "<int:blog_id>/comment/<int:pk>/edit",
        views.EditCommentView.as_view(),
        name="edit-comment",
    ),
    path(
        "<int:blog_id>/comment/<int:pk>/detele",
        views.DeleteCommentView.as_view(),
        name="delete-comment",
    ),
]

miniblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from .views import sign_up_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]


urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', sign_up_user, name="signup"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone


class Author(models.Model):

    bio = models.TextField("Description about the author")
    date_of_birth = models.DateField()

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse("author-detail", kwargs={"pk": self.pk})


class Blog(models.Model):

    title = models.CharField(max_length=200, verbose_name="Blog Title")
    post_date = models.DateTimeField("Posted Date", auto_now_add=True)
    blogger = models.ForeignKey(
        "Author",
        verbose_name="Author of the blog",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog-detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-post_date"]


class Content(models.Model):

    text = models.TextField("Content text")
    blog = models.ForeignKey(
        "Blog", verbose_name="Content's blog", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.text


class Comment(models.Model):

    text = models.TextField("Comment text")
    blog = models.ForeignKey(
        "Blog", verbose_name="Comment's blog", on_delete=models.SET_NULL, null=True
    )

    comment_date = models.DateTimeField("Commented Date")

    user = models.ForeignKey(
        User, verbose_name="Commented By", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ["-comment_date"]

blog/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import Blog, Content


class BlogModelForm(forms.ModelForm):
    class Meta:
        model = Blog

        fields = ("title",)

        widgets = {"title": forms.TextInput(attrs={"placeholder": "A beautiful blog!"})}


ContentFormSet = modelformset_factory(
    Content,
    fields=("text",),
    extra=2,
    widgets={"text": forms.TextInput(attrs={"placeholder": "New content goes here"})},
)

blog/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.db import transaction
from .models import Author, Blog, Comment, Content
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)

from .forms import BlogModelForm, ContentFormSet

import datetime


def index(request):

    total_number_of_blogs = Blog.objects.count()
    total_number_of_authors = Author.objects.count()

    context = {
        "total_number_of_blogs": total_number_of_blogs,
        "total_number_of_authors": total_number_of_authors,
    }

    return render(request, "index.html", context)


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5


class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author


class BlogDetailView(generic.DetailView):
    model = Blog


class AddCommentView(LoginRequiredMixin, CreateView):

    model = Comment
    fields = ["text"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_blog = Blog.objects.get(pk=self.kwargs["blog_id"])
        context["blog"] = current_blog
        return context

    def form_valid(self, form):
        current_date = datetime.date.today()
        form.instance.user = self.request.user
        form.instance.comment_date = current_date

        current_blog = Blog.objects.get(pk=self.kwargs["blog_id"])
        form.instance.blog = current_blog

        return super(AddCommentView, self).form_valid(form)

    def get_success_url(self):
        return reverse("blog-detail", kwargs={"pk": self.kwargs["blog_id"]})


class EditCommentView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    model = Comment
    fields = ["text"]

    def test_func(self):
        id = self.kwargs["pk"]
        user_comment = Comment.objects.get(pk=id)
        return self.request.user == user_comment.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_blog = Blog.objects.get(pk=self.kwargs["blog_id"])
        context["blog"] = current_blog
        return context

    def form_valid(self, form):
        current_date = datetime.date.today()
        form.instance.user = self.request.user
        form.instance.comment_date = current_date

        current_blog = Blog.objects.get(pk=self.kwargs["blog_id"])
        form.instance.blog = current_blog

        return super(EditCommentView, self).form_valid(form)

    def get_success_url(self):
        return reverse("blog-detail", kwargs={"pk": self.kwargs["blog_id"]})


class DeleteCommentView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        id = self.kwargs["pk"]
        user_comment = Comment.objects.get(pk=id)
        return self.request.user == user_comment.user

    def get_success_url(self):
        return reverse("blog-detail", kwargs={"pk": self.kwargs["blog_id"]})


def create_blog_view(request):
    template_name = "blog/blog_form.html"

    if request.method == "GET":
        blog_form = BlogModelForm(request.GET or None)
        formset = ContentFormSet(queryset=Content.objects.none())

    elif request.method == "POST":
        blog_form = BlogModelForm(request.POST)
        formset = ContentFormSet(request.POST)

        if blog_form.is_valid() and formset.is_valid():

            blog = blog_form.save()

            author = Author.objects.get(user=request.user)
            blog.blogger = author

            blog.save()

            for form in formset:

                content = form.save(commit=False)
                content.blog = blog
                content.save()

            return redirect("blogs")

    return render(request, template_name, {"blog_form": blog_form, "formset": formset})


class EditBlogView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Blog
    template_name = "blog/blog_edit_form.html"
    fields = ("title",)

    def test_func(self):
        id = self.kwargs["pk"]
        user_blog = Blog.objects.get(pk=id)
        return self.request.user == user_blog.blogger.user

    def get_success_url(self):
        return reverse("blog-detail", kwargs={"pk": self.kwargs["pk"]})


class DeleteBlogView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Blog

    def test_func(self):
        id = self.kwargs["pk"]
        user_blog = Blog.objects.get(pk=id)
        return self.request.user == user_blog.blogger.user

    def get_success_url(self, **kwargs):
        return reverse("blogs")


class EditContentView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Content
    fields = ("text",)
    template_name = "blog/content_edit_form.html"

    def test_func(self):
        id = self.kwargs["blog_id"]
        user_blog = Blog.objects.get(pk=id)
        return self.request.user == user_blog.blogger.user

    def get_success_url(self):
        return reverse("blog-detail", kwargs={"pk": self.kwargs["blog_id"]})


class DeleteContentView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Content

    def test_func(self):
        id = self.kwargs["blog_id"]
        user_blog = Blog.objects.get(pk=id)
        return self.request.user == user_blog.blogger.user

    def get_success_url(self):
        return reverse("blog-detail", kwargs={"pk": self.kwargs["blog_id"]})

blog/templates/blog/author_detail.html
{% extends 'base_generic.html' %} {% block title %} {{ author.name }} 
{% endblock title %} {% block content %}

<div class="blog-header">
  <h2>{{author.user.get_full_name}}</h2>
  <p>
    Date of Birth: 
    <i>{{author.date_of_birth}} </i>
  </p>
  <p>{{author.bio}}</p>
</div>


<h5>Blogs</h5>
<hr>

<div class="blog-contents">
  {% for blog in author.blog_set.all %}

  <div class="blog">
    <a href="{% url 'blog-detail' blog.pk %}"><h5>{{blog.title}}</h5></a>
    <p>
      <i>{{blog.post_date}} </i>
    </p>
    <p>
        {{blog.content_set.all.0.text}}
    </p>
  </div>

  {% endfor %}
</div>

{% endblock content %}

blog/templates/blog/author_list.html
{% extends 'base_generic.html' %} 
{% block title %}
Authors 
{% endblock title %}

{% block content %}

<h2>Authors</h2>

{% if author_list %}

<ul>
  {% for author in author_list %}

  <div class="author">
    <a href="{% url 'author-detail' author.pk %}"><h5>{{author.user.get_full_name}}</h5></a>
    <p>
      Date of Birth:
      <strong>
          {{author.date_of_birth}}
      </strong>
    </p>
  </div>

  {% endfor %}
</ul>

{% else %}

<p>
  <i>No authors found!</i>
</p>

{% endif %} {% endblock content %}

blog/templates/blog/blog_confirm_delete.html
{% extends "base_generic.html" %} {% block content %}

<h1>Delete Comment</h1>

<p>Are you sure want to delete the blog: <strong> {{blog.title}} </strong>?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, Delete" />
</form>

{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends 'base_generic.html' %}
{% block title %} 
{{ blog.title }} {% endblock title %}

{% block content %} 

<div class="blog-header">
  <div class="info">
    <h2>{{blog.title}}</h2>
    <p>
      written by
      <strong>
        <a href="{% url 'author-detail' blog.blogger.pk %}">
          {{blog.blogger.user.get_full_name}}
        </a>
      </strong>
      |
      <i>{{blog.post_date}} </i>
    </p>
  </div>
  {% if request.user == blog.blogger.user %}
    <div class="action">
      <a href="{% url 'edit-blog' blog.pk %}" class="edit">Edit</a>
      <a href="{% url 'delete-blog' blog.pk %}" class="delete">Delete</a>
    </div>
  {% endif %}
</div>

<div class="blog-contents">

    
    {% for content in blog.content_set.all %}

    <div class="content-block">
      <p>
          {{content.text}}
      </p>

      
      {% if request.user == blog.blogger.user %}
        <div class="action">
          <a href="{% url 'edit-content' blog.pk content.pk %}" class="edit">Edit</a>
          <a href="{% url 'delete-content' blog.pk content.pk %}" class="delete">Delete</a>
        </div>
      {% endif %}
    </div>


    {% endfor %}
        

</div>

<h4>Comments</h4>
<hr>



<div class="comments">

  
  {% for comment in blog.comment_set.all %}
    
    <div class="comment">

      <h6> {{comment.user.get_full_name}} </h6>
      <i> {{comment.comment_date}} </i>
      {% if comment.user == request.user %}
      &nbsp;
      <a href="{% url 'edit-comment' blog.pk comment.pk %}">Edit</a> • 
      <a href="{% url 'delete-comment' blog.pk comment.pk %}">Delete</a>
        
      {% endif %}
      <p>
        {{comment.text}}
      </p>

    </div>

  {% endfor %}

  
  {% if user.is_authenticated %}

    <a href="{% url 'add-comment' blog.pk %}">Add a new Comment</a>

  {% else %}

    You should be logged in to add a comment. Please <a href="{% url 'login' %}?next={{request.path}}">Login</a>

  {% endif %}

    

</div>

{% endblock content %}

blog/templates/blog/blog_edit_form.html
{% extends "base_generic.html" %} {% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <table>
    {{form.as_table}}
  </table>

  <input type="submit" value="Submit" />
</form>

{% endblock content %}

blog/templates/blog/blog_form.html
{% extends 'base_generic.html' %} {% block content %}

<form action="" method="POST" class="add-blog">
  {% csrf_token %}

  <div class="inputs">
    <div class="input-wrapper">
      <p>Title</p>
      {{blog_form.title}}
    </div>

    {{formset.management_form}}
    <p>Contents</p>

    {% for form in formset %}
    <div class="input-wrapper form-row">
      {{form.text}}
      <input class="remove-form-row" type="button" value="-" />
    </div>
    {% endfor %}
    <div class="add-content-wrapper">
      <button class="add-form-row">Add Content</button>
    </div>
  </div>

  <div class="create-btn-wrapper">
    <button type="submit" class="create-btn">Create</button>
  </div>
</form>

<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"
></script>

<script type="text/javascript">
  function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp("(" + prefix + "-\\d+)");
    var replacement = prefix + "-" + ndx;
    if ($(el).attr("for"))
      $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
  }

  function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $("#id_" + prefix + "-TOTAL_FORMS").val();
    newElement
      .find(":input:not([type=button]):not([type=submit]):not([type=reset])")
      .each(function () {
        var name = $(this)
          .attr("name")
          .replace("-" + (total - 1) + "-", "-" + total + "-");
        var id = "id_" + name;
        $(this).attr({ name: name, id: id }).val("").removeAttr("checked");
      });
    newElement.find("label").each(function () {
      var forValue = $(this).attr("for");
      if (forValue) {
        forValue = forValue.replace("-" + (total - 1) + "-", "-" + total + "-");
        $(this).attr({ for: forValue });
      }
    });
    total++;
    $("#id_" + prefix + "-TOTAL_FORMS").val(total);
    $(selector).after(newElement);
    var conditionRow = $(".form-row:not(:last)");
    conditionRow
      .find(".btn.add-form-row")
      .removeClass("btn-success")
      .addClass("btn-danger")
      .removeClass("add-form-row")
      .addClass("remove-form-row")
      .html(
        '<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>'
      );
    return false;
  }
  function deleteForm(prefix, btn) {
    var total = parseInt($("#id_" + prefix + "-TOTAL_FORMS").val());
    if (total > 1) {
      btn.closest(".form-row").remove();
      var forms = $(".form-row");
      $("#id_" + prefix + "-TOTAL_FORMS").val(forms.length);
      for (var i = 0, formCount = forms.length; i < formCount; i++) {
        $(forms.get(i))
          .find(":input")
          .each(function () {
            updateElementIndex(this, prefix, i);
          });
      }
    }
    return false;
  }
  $(document).on("click", ".add-form-row", function (e) {
    e.preventDefault();
    cloneMore(".form-row:last", "form");
    return false;
  });
  $(document).on("click", ".remove-form-row", function (e) {
    e.preventDefault();
    deleteForm("form", $(this));
    return false;
  });
</script>

{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'base_generic.html' %} 
{% block title %}
Blogs 
{% endblock title %}

{% block content %}
<h2>Blogs</h2>

{% if blog_list %}

<ul>
  {% for blog in blog_list %}

  <div class="blog">
    <a href="{% url 'blog-detail' blog.pk %}"><h5>{{blog.title}}</h5></a>
    <p>
      written by
      <strong>
        <a href="{% url 'author-detail' blog.blogger.pk %}">
          {{blog.blogger.user.get_full_name}}
        </a>
      </strong>
      |
      <i>{{blog.post_date}} </i>
    </p>
    <p>Comments: {{blog.comment_set.count}}</p>
  </div>

  {% endfor %}
</ul>

{% else %}

<p>
  <i>No blogs found!</i>
</p>

{% endif %} {% endblock content %}

blog/templates/blog/comment_confirm_delete.html
{% extends "base_generic.html" %} {% block content %}

<h1>Delete Comment</h1>

<p>Are you sure want to delete the book: <strong> {{comment}} </strong>?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, Delete" />
</form>

{% endblock content %}

blog/templates/blog/comment_form.html
{% extends "base_generic.html" %} {% block content %}

<p>You're commenting on <a href="{% url 'blog-detail' blog.pk %}"> {{blog.title}} </a> </p>

<form action="" method="POST">
  {% csrf_token %}

  <table>
    {{form.as_table}}
  </table>

  <input type="submit" value="Submit" />
</form>

{% endblock content %}

blog/templates/blog/content_confirm_delete.html
{% extends "base_generic.html" %} {% block content %}

<h1>Delete Comment</h1>

<p>Are you sure want to delete the content? <br> <strong> {{content.text}} </strong></p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, Delete" />
</form>

{% endblock content %}

blog/templates/blog/content_edit_form.html
{% extends "base_generic.html" %} {% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <table>
    {{form.as_table}}
  </table>

  <input type="submit" value="Submit" />
</form>

{% endblock content %}